steps:
  - name: ':hammer: Build Android RoktWebView SDK'
    commands:
      - bundle install
      - bundle exec fastlane buildAndroidSdkForPR
    artifact_paths:
      - app/**/*.apk
      - roktwebviewsdk/**/*.aar
    plugins:
      - 'docker-compose#v3.0.0':
          config: ./docker-compose.yml
          run: build_android
      - 'seek-oss/aws-sm#v2.0.0':
          env:
            STORE_PASSWORD:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .STORE_PASSWORD
            KEY_ALIAS:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .KEY_ALIAS
            KEY_PASSWORD:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .KEY_PASSWORD
    agents:
      queue: stage-us-west-2-default
    timeout_in_minutes: 25
  - name: ':hammer: Test Android RoktWebView SDK'
    commands:
      - bundle install
      - bundle exec fastlane test
    artifact_paths:
      - roktwebviewsdk/build/test-results/**/*.xml
    plugins:
      - 'docker-compose#v3.0.0':
          config: ./docker-compose.yml
          run: build_android
    agents:
      queue: eng-default
    timeout_in_minutes: 25
  - name: ':pipeline: Dev'
    commands:
      - buildkite-agent pipeline upload .buildkite/pipeline-dev.yml
    agents:
      queue: eng-default
    branches: '!release-*'
  - name: ':pipeline: Release'
    commands:
      - buildkite-agent pipeline upload .buildkite/pipeline-prod.yml
    agents:
      queue: eng-default
    branches: release-*
  - input: ':whale: Release to Maven'
    prompt: Confirm releasing this version to Maven?
    key: block-release-maven
  - name: ':speech_balloon: Notify Maven repository deployment start'
    depends_on: block-release-maven
    command:
      - echo "Notify gchat"
    plugins:
      - 'seek-oss/aws-sm#v2.0.0':
          env:
            NOTIFICATION_ENDPOINT:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .NOTIFICATION_ENDPOINT
            CHAT_WEBHOOK:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .CHAT_WEBHOOK
      - 'ROKT/hangouts-notify#v0.6':
          env: CHAT_WEBHOOK NOTIFICATION_ENDPOINT
          chat-endpoint: NOTIFICATION_ENDPOINT
          webhook-url: CHAT_WEBHOOK
          message: >-
            *RoktWebViewSDK Android* publishing the SDK to Maven
            repository\n${BUILDKITE_BUILD_URL}\n_by ${BUILDKITE_BUILD_CREATOR}_
    agents:
      queue: stage-us-west-2-default
  - name: ':rocket: Publish RoktWebView SDK to maven'
    depends_on: block-release-maven
    commands:
      - bundle install
      - bundle exec fastlane publishToBintray
    artifact_paths:
      - app/**/*.apk
      - roktwebviewsdk/**/*.aar
    plugins:
      - 'docker-compose#v3.0.0':
          config: ./docker-compose.yml
          run: build_android
      - 'seek-oss/aws-sm#v2.0.0':
          env:
            STORE_PASSWORD:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .STORE_PASSWORD
            KEY_ALIAS:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .KEY_ALIAS
            KEY_PASSWORD:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .KEY_PASSWORD
            BINTRAY_USER:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .BINTRAY_USER
            BINTRAY_KEY:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .BINTRAY_KEY
    agents:
      queue: stage-us-west-2-default
    timeout_in_minutes: 25
  - wait
  - name: ':speech_balloon: Notify Maven repository deployment complete'
    command:
      - echo "Notify gchat done"
    plugins:
      - 'ROKT/hangouts-notify#v0.6':
          chat-endpoint: '${NOTIFICATION_ENDPOINT}'
          webhook-url: '${CHAT_WEBHOOK}'
          message: >-
            *RoktWebViewSDK Android* publishing the SDK to Maven repository
            complete
    agents:
      queue: eng-default
