# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "roktwebviewsdk:testDebugUnitTest")
  end

  desc "Build & Unit Test Android SDK for PR build"
  lane :buildAndroidSdkForPR do
    # Build android flavours and unit test
    gradle(task: "roktwebviewsdk:assemble")
    gradle(task: "roktwebviewsdk:ktlintCheck")
    gradle(task: "assemble")
    gradle(task: "ktlintCheck")
  end

  desc "Publish SDK to PROD maven repo"
  lane :publishToBintray do
    gradle(task: "roktwebviewsdk:clean")
    gradle(task: "roktwebviewsdk:build")
    gradle(task: "roktwebviewsdk:bintrayUpload")
  end
end
